name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install prerequisites
        run: sudo apt-get install -y check

      - name: Build tests
        run: make test

      - name: Run tests
        run: make run-tests

      - name: Build example
        run: make example

      - name: Run example
        run: make run-example